### ISSUE TITLE
Usage of deprecated (and now removed) python function platform.linux_distribution

### ISSUE THREAD

**Issue by mbdevpl** [intelxed/mbuild#28]
In this file https://github.com/intelxed/mbuild/blob/master/mbuild/env.py#L445 a function `platform.linux_distribution` is used. According to the python documentation at https://docs.python.org/3.7/library/platform.html#platform.linux_distribution:

> Deprecated since version 3.5, will be removed in version 3.8: See alternative like the [distro](https://pypi.org/project/distro) package.

And indeed on my system with Python 3.8 there's no such function.

**Comment by markcharney** [comment]
Thanks. Yeah. I have a patch for this. I noticed it when I upgrade to python3.8. I will push it out later today

**Comment by markcharney** [comment]
Turns out I already had this on a branch (mjc/2019-10-15), but I pushed another branch just now with a potential improvement for another unrelated issue.  

#29

**Comment by markcharney** [comment]
pull from master; should be fixed now. Let me know if you encounter other issues. thx

**Comment by markcharney** [comment]
BTW, if you do want the linux distro information, there is a comment in the code:

-            # People who require it can "python3 -m pip install distro"

The import for that module is in try/except block so if it is not present, mbuild just assumes a generic linux distribution.
