### ISSUE TITLE
race condition when using anaconda python

### ISSUE THREAD

**Issue by rscohn2** [intelxed/mbuild#4]
Race condition!?

Install anaconda:

(asv) rscohn1@fxsatlin01$ wget -q https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
(asv) rscohn1@fxsatlin01$ chmod +x Miniconda2-latest-Linux-x86_64.sh
(asv) rscohn1@fxsatlin01$ ./Miniconda2-latest-Linux-x86_64.sh -b -p ~/tmp/mymini

Download mbuild and install it:

(asv) rscohn1@fxsatlin01$ git clone https://github.com/intelxed/mbuild.git
Cloning into 'mbuild'...
remote: Counting objects: 66, done.        
remote: Compressing objects: 100% (44/44), done.        
remote: Total 66 (delta 18), reused 65 (delta 17), pack-reused 0        
Unpacking objects: 100% (66/66), done.
Checking connectivity... done.
(asv) rscohn1@fxsatlin01$ /tmp/mymini/bin/pip install -e  mbuild
Obtaining file:///localdisk/work/rscohn1/workspaces/mbuild
Installing collected packages: mbuild
  Running setup.py develop for mbuild
Successfully installed mbuild-0.2496
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

3.py test randomly fails. Looks like you are not waiting for all threads to end?

(asv) rscohn1@fxsatlin01$ /tmp/mymini/bin/python 3.py 
[INVOKED] 3.py
[START TIME] 2016-12-19 09_36_33 CST
[CURRENT DIRECTORY] /localdisk/work/rscohn1/workspaces/mbuild/tests
[UNAME] ('Linux', 'fxsatlin01', '3.13.0-85-generic', '#129-Ubuntu SMP Thu Mar 17 20_50_15 UTC 2016', 'x86_64', 'x86_64')
[SYSTEM] Linux
[HOSTNAME] fxsatlin01
[BUILD_OS] lin
[BUILD_CPU] x86-64
[HOST_OS] lin
[HOST_CPU] x86-64
[HOST_CPU] x86-64
[BUILD] succeeded
(asv) rscohn1@fxsatlin01$ /tmp/mymini/bin/python 3.py 
[INVOKED] 3.py
[START TIME] 2016-12-19 09_36_35 CST
[CURRENT DIRECTORY] /localdisk/work/rscohn1/workspaces/mbuild/tests
[UNAME] ('Linux', 'fxsatlin01', '3.13.0-85-generic', '#129-Ubuntu SMP Thu Mar 17 20_50_15 UTC 2016', 'x86_64', 'x86_64')
[SYSTEM] Linux
[HOSTNAME] fxsatlin01
[BUILD_OS] lin
[BUILD_CPU] x86-64
[HOST_OS] lin
[HOST_CPU] x86-64
[HOST_CPU] x86-64
[BUILD] succeeded
(asv) rscohn1@fxsatlin01$ /tmp/mymini/bin/python 3.py 
[INVOKED] 3.py
[START TIME] 2016-12-19 09_36_36 CST
[CURRENT DIRECTORY] /localdisk/work/rscohn1/workspaces/mbuild/tests
[UNAME] ('Linux', 'fxsatlin01', '3.13.0-85-generic', '#129-Ubuntu SMP Thu Mar 17 20_50_15 UTC 2016', 'x86_64', 'x86_64')
[SYSTEM] Linux
[HOSTNAME] fxsatlin01
[BUILD_OS] lin
[BUILD_CPU] x86-64
[HOST_OS] lin
[HOST_CPU] x86-64
[HOST_CPU] x86-64
[BUILD] succeeded
Exception in thread Thread-4 (most likely raised during interpreter shutdown):
(asv) rscohn1@fxsatlin01$

**Comment by markcharney** [comment]
thx. repo'd. intermittent. I have seen this before.

**Comment by markcharney** [comment]
fixed in #5 .
